version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gestion-billar
    working_dir: /var/www/html/
    restart: always
    container_name: gestion-billar
    hostname: gestion-billar
    ports:
      - "${GESTION_PORT}:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - billar-network

networks:
  billar-network:
    external: true